Integrate janus package
FormingWorlds/PROTEUS pull request #109
Opened 2024-07-18 14:54 UTC by lsoucasse

This work links Proteus with Janus as a package. Main differences are that Socrates is now a separate submodule and that input spectral data are downloaded from the OSF.

The main Proteus script seems to run fine but it might be worth checking it again.

2024-07-18 15:00 UTC, nichollsh requested changes
Looks great except for my 1 comment on the FWL_DATA variable.
The model seems to run fine on my machine too.

2024-07-18 15:00 UTC, nichollsh commented on PROTEUS.env
>  export FWL_DATA=$COUPLER_DIR/fwl_data/
I am not sure that this is a good idea. For example, I do not place my FWL data folder in this location. We could leave it as a default, but it might better to force the user to set the variable themselves, or encourage them to put it in their bashrc.

2024-07-19 07:19 UTC, lsoucasse commented on PROTEUS.env
>  export FWL_DATA=$COUPLER_DIR/fwl_data/
My idea was that it was safer for basic users. I agree it gives more flexibility to set it separately (I also store my fwl_data folder in another place). New commit should fix it.

2024-07-19 07:22 UTC, nichollsh approved these changes

2024-07-19 07:23 UTC, nichollsh commented
Closes #100, I assume

2024-07-19 07:28 UTC, lsoucasse commented
> Closes #100, I assume?

Thanks @nichollsh! Yes, the issue is linked with the branch and PR.

2024-07-19 07:28 UTC, merged