Fix * imports
FormingWorlds/PROTEUS pull request #138
Opened 2024-08-12 08:28 UTC by stefsmeets

This PR fixes all the `from x import *` imports. Avoiding * imports is generally considered a [good practice](https://peps.python.org/pep-0008/#imports). I used [`ruff`](https://docs.astral.sh/ruff/rules/#isort-i) to help with the formatting, partly addressing #131 as well. 

To find import issues, you can use:

```
ruff check start_proteus.py  # single file
ruff check src/proteus       # directory
ruff check .                 # everything
```

Prepend `--fix` to sort imports and remove unused imports:

```
ruff check . --fix
```

I also set up a small [pre-commit](https://pre-commit.com/#usage) config so you can automatically have it sort imports on every commit, e.g.:

```
pre-commit install
```

Closes #136
Addresses #131

### Todo
- [ ] Setup github action
- [ ] Add documentation

2024-08-12 10:02 UTC, stefsmeets commented
Hi @nichollsh @timlichtenberg This PR is ready, could you have a look and let me know what you think?

Could you test it with some of your workflows to make sure no imports were missed?

2024-08-19 12:50 UTC, lsoucasse commented on start_proteus.py
> +from proteus.utils.logs import (
```suggestion
from proteus.utils.helper import (
    CleanDir,
    PrintHalfSeparator,
    PrintSeparator,
    safe_rm,
    UpdateStatusfile,
)
from proteus.utils.logs import (
```

2024-08-19 12:51 UTC, lsoucasse commented on start_proteus.py
>  from proteus.atmos_clim import RunAtmosphere
```suggestion
from proteus.atmos_clim import RunAtmosphere
from proteus.atmos_clim.agni import DeallocAtmos
```

2024-08-19 12:53 UTC, lsoucasse requested changes
Hi @stefsmeets, I spotted some missing imports. The default config script runs fine for me.

2024-08-19 13:35 UTC, stefsmeets commented
Hi @lsoucasse thanks for pointing those out, I fixed the issues.

2024-08-19 13:44 UTC, merged