Refactor start_proteus.py and move config to toml
FormingWorlds/PROTEUS pull request #142
Opened 2024-08-20 14:23 UTC by stefsmeets

This PR refactors the `start_proteus.py`. This includes an update to the CLI, in line with what we did for janus / mors.

```console
proteus start --config input/default.toml
```

or

```console
python start_proteus.py
```

I also started to move the config to toml. Moving to toml was fairly straightforward and only meant minor changes in the cfg files itself. Many parts of the code read the config directly, which is turned out to be more work than I had anticipated.

Next steps would be to break down the `Proteus.start()` function into isolated methods, but I want to tackle that in a follow-up PR to avoid making too many changes at once.

## TODO
- [ ] Update `plot/cpl_*` files to use toml.

2024-08-22 09:45 UTC, stefsmeets commented
Hi @lsoucasse @nichollsh Could you please review this PR and let me know what you think?

The main files to look at would be `src/proteus/proteus.py`, `src/proteus/cli.py`, `src/proteus/utils/coupler.py`.

Because of the toml change, I also had to update all the code that reads in the config directly, see `src/proteus/plot`, and specifically `_cpl_helpers.py` for how I refactored it.

Happy to talk you through the PR if necessary.

2024-08-23 13:31 UTC, nichollsh commented
Looks good. These changes make sense to me, and it's nice to have a consistent CLI for PROTEUS.

However, doesn't this make `start_proteus.py` redundant? Why include it at all if there's already the `click` interface for running the model via `proteus start`?

2024-08-26 07:36 UTC, lsoucasse commented on docs/usage.md
> +located at `input/default.toml` will be used. Pass the flag `--resume` in
The config file is always expected by the cli function.

2024-08-26 07:41 UTC, lsoucasse requested changes
Thanks @stefsmeets, Nice to switch to toml and to have the cli for running proteus. I agree for now the start_proteus.py script is redundant but once we split the big running function into different methods it might be worth having it.
I tested all the commands, it seems to run fine. Just need to update the documentation because the path to config file is mandatory for the cli.

2024-08-26 08:00 UTC, stefsmeets commented on docs/usage.md
> +located at `input/default.toml` will be used. Pass the flag `--resume` in
Good catch, I will change it.

2024-08-26 08:03 UTC, stefsmeets commented
Cheers both, agree on the `start_proteus.py`. I kept it, because it signals how to call the code from Python. And it is part of the current workflow for some people. I think it does not hurt to keep it around for a while, but if you both think we can remove it we can also remove it.

2024-08-26 08:29 UTC, lsoucasse commented
> Cheers both, agree on the `start_proteus.py`. I kept it, because it signals how to call the code from Python. And it is part of the current workflow for some people. I think it does not hurt to keep it around for a while, but if you both think we can remove it we can also remove it.

I think we can keep it for now.

2024-08-26 11:36 UTC, stefsmeets commented
@nichollsh @lsoucasse Could you check again and approve? This PR is ready to be merged.

2024-08-26 12:03 UTC, lsoucasse approved these changes
Good for me.

2024-08-26 13:06 UTC, merged