Add validators to config
FormingWorlds/PROTEUS pull request #223
Opened 2024-10-22 09:39 UTC by stefsmeets

This PR adds validation to the config file. I'm using https://github.com/FormingWorlds/PROTEUS/blob/main/docs/config_old.md, which nicely lists all the domains, as a basis.

Closes #200

2024-10-22 15:00 UTC, nichollsh requested changes
Looks good overall. I added a few comments for minor changes.

2024-10-22 15:00 UTC, nichollsh commented on input/jgr_grid.toml
> -        S_ppmw      = 0.0       # Sulfur inventory in ppmw relative to mass of melt
This should be left at zero because it's the value that was used when the grid was run.

2024-10-22 15:00 UTC, nichollsh commented on input/hd63433d.toml
> -            F_crit   = 1.8        # Maximum absolute value of F_atm allowed for convergence
Please leave this one at 1.8

2024-10-22 15:00 UTC, nichollsh commented on src/proteus/config/_delivery.py
> +    S_ppmw: float = field(validator=gt(0))
N_ppmw and S_ppmw are allowed to equal zero.

2024-10-22 15:00 UTC, nichollsh commented on src/proteus/config/_params.py
> +    initial: float = field(validator=ge(0))
Step sizes should be greater than zero, since we cannot allow dt=0.

2024-10-22 16:20 UTC, stefsmeets commented on input/hd63433d.toml
> -            F_crit   = 1.8        # Maximum absolute value of F_atm allowed for convergence
What should the range be then? Currently it is 0-1

2024-10-22 16:52 UTC, nichollsh commented on input/hd63433d.toml
> -            F_crit   = 1.8        # Maximum absolute value of F_atm allowed for convergence
The valid range for `F_crit` and `dprel` is >0.

2024-10-22 16:52 UTC, nichollsh commented on input/jgr_grid.toml
> -        S_ppmw      = 0.0       # Sulfur inventory in ppmw relative to mass of melt
@stefsmeets: note that the value of 300 ppmw is fine for the other configs. It's just this one that needs to be zero.

2024-10-23 07:28 UTC, stefsmeets commented
Thanks @nichollsh , let me know if you are happy with the PR now!

2024-10-23 07:30 UTC, nichollsh approved these changes

2024-10-23 07:31 UTC, merged